language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t dockerimage-routing -f Dockerfile.prod .
script:
    - docker push $DOCKER_USERNAME/dockerimage-routing
    - docker run -e CI=true dockerimage-routing

after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag back $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USER/back:$TRAVIS_BUILD_NUMBER
    - docker tag back $DOCKER_USER/back:latest
    - docker push $DOCKER_USER/back:latest
